export const RECIVE_ADDRESS = 'recive_address'
export const RECIVE_CATEGORY = 'recive_category'
export const RECIVE_SHOPS = 'recive_shops'
export const RECIVE_USERINFO = 'recive_userInfo'
export const OUT_USERINFO = 'out_userinfo'
export const RECEIVE_GOODS = 'receive_goods' // 接收商品数组
export const RECEIVE_RATINGS = 'receive_ratings' // 接收商家评价数组
export const RECEIVE_INFO = 'receive_info' // 接收商家信息
export const INCREASE_COUNT = 'increase_count' //增加food.count的值
export const DECREASE_COUNT = 'decrease_count' //减少food.count的值
export const CLEAR_SHOPCART = 'clear_shopcart' //清空购物车shopCart的值
export const RECEIVE_SEARCH_SHOPS = 'receive_search_shops' // 接收搜索的商品数组
